### ISSUE TITLE
Files are wrongfully counted as test files 

### ISSUE THREAD

**Issue by aerodynamica** [microsoft/PR-Metrics#254]
## Summary
A file like Duplica**teSt**orageItemPlugin.java is considered as a test file because it contains the word test, even though the camel casing shows it's clearly not a test file.

## Reproduction Steps

Calculate the metrics for a pull request where a file with a name like Duplica**teSt**orageItemPlugin.java is one of the added/edited files.

**Comment by muiriswoulfe** [comment]
Thanks @aerodynamica for using PR Metrics and for letting us know about the issue. I've now got a PR out – linked above – which should resolve the issue.

Note that PR Metrics is designed to provide a quick and robust determination of the metrics rather than a slow but accurate determination. Therefore, it is possible and acceptable that the new algorithm will still detect false positives. But overall, it should be much more accurate, and it will resolve the issue you detected.
