### ISSUE TITLE
Request for ignoring white spaces while computing diff count.

### ISSUE THREAD

**Issue by armaanverma123** [microsoft/PR-Metrics#356]
## Summary
We have a typescript codebase, wrapping a component with a wrapper changes the indentation due to linters of the whole codebase. Can this tool avoid the white space changes in the lines for non-padding sensitive languages.

This ends up tagging the PR with a very abrupt size although the Azure Devops PR viewer shows the diff count as a few lines.

**Comment by muiriswoulfe** [comment]
Hi @armaanverma123. Thanks for using PR Metrics and contributing your feedback.

We're aware of the issue you've outlined, but it's unfortunately something that is out of scope for PR Metrics. PR Metrics is designed to run very quickly to avoid slowing down CI/CD loops. So, to achieve this, we get the information from running a Git command. Since Git is only interested in line changes, that is all that Git can give us back.

I'm aware that Azure DevOps shows a different count and I've investigated using this in the past. However, Azure DevOps is surfacing this information using an undocumented API. If we were to call this, there is no guarantee that it would change in the future at an unexpected time.

It should also be noted that PR Metrics is language agnostic, to make it work for all languages. So, we don't have a concept of which languages are padding or non-padding sensitive.

Therefore, the only solution here is unfortunately to maintain the current behavior.

**Comment by armaanverma123** [comment]
Hey @muiriswoulfe 
So it looks like the -w flag from GIT should help resolve this issue. Would accepting some input config to edit this command that you run to get the diff help solve this issue?

**Comment by muiriswoulfe** [comment]
Good catch @armaanverma123. I'll look into that further shortly.

**Comment by muiriswoulfe** [comment]
I've now got a PR out for this as you can see above. Thanks for your suggestion.
