### ISSUE TITLE
Request: Make PR comment table horizontal vs vertical

### ISSUE THREAD

**Issue by houserx-jmcc** [microsoft/PR-Metrics#399]
## Summary

Make the metrics table horizontal vs vertical to save space. This could be an optional format, or just the new default one.

## Rationale

When there is a lot of activity in a pull request on GitHub, vertical screen real estate can quickly be eaten up by various Actions and bot comments. By switching the format of the PR metrics table, we can quickly re-gain some of that space.

## Additional Information

Current:

||Lines
-|-:
Product Code|0
Test Code|2
**Subtotal**|**2**
Ignored Code|23
**Total**|**25**

Proposed:

|| Product Code | Test Code | Subtotal | Ignored Code | Total |
-|-|-|-|-|-|
|Lines | 0 | 2|  2 | 23 | 25

**Comment by muiriswoulfe** [comment]
Hi @houserx-jmcc,

Thanks for your feedback. I understand the issue you have identified, but unfortunately, this change is out of scope for the project. The reasons are:

- Table is less clear in the horizontal format, as it is harder to determine what the subtotal and total reference since the row titles of these will no longer be in bold.
- Table is less accessible as the format is reversed from the standard table format, and Markdown limitations mean that this cannot be easily remediated.
- There is unlikely to be widespread usage of this table format.
- The issue you've identified is arguably an issue with GitHub UX rather than PR Metrics. You could potentially use a [Tampermonkey](https://www.tampermonkey.net/) script to help resolve this or file an issue to GitHub.

I understand that we can provide an option for switching between table formats as you identified, but we don't have the bandwidth for adding and supporting features that we do not envisage being of widespread use. If there is additional demand for this, it's something we can reconsider, but at the moment, we cannot justify this addition.

Thanks once more for your contribution.
